package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dan generated by hbm2java
 */
public class Dan  implements java.io.Serializable {


     private DanId id;
     private Festival festival;
     private int brKarata;
     private int brProdatihKarata;
     private int brRezervisanihKarata;
     private Set<Nastupa> nastupas = new HashSet<Nastupa>(0);
     private Set<Rezervacija> rezervacijas = new HashSet<Rezervacija>(0);

    public Dan() {
    }

	
    public Dan(DanId id, Festival festival, int brKarata, int brProdatihKarata, int brRezervisanihKarata) {
        this.id = id;
        this.festival = festival;
        this.brKarata = brKarata;
        this.brProdatihKarata = brProdatihKarata;
        this.brRezervisanihKarata = brRezervisanihKarata;
    }
    public Dan(DanId id, Festival festival, int brKarata, int brProdatihKarata, int brRezervisanihKarata, Set<Nastupa> nastupas, Set<Rezervacija> rezervacijas) {
       this.id = id;
       this.festival = festival;
       this.brKarata = brKarata;
       this.brProdatihKarata = brProdatihKarata;
       this.brRezervisanihKarata = brRezervisanihKarata;
       this.nastupas = nastupas;
       this.rezervacijas = rezervacijas;
    }
   
    public DanId getId() {
        return this.id;
    }
    
    public void setId(DanId id) {
        this.id = id;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public int getBrKarata() {
        return this.brKarata;
    }
    
    public void setBrKarata(int brKarata) {
        this.brKarata = brKarata;
    }
    public int getBrProdatihKarata() {
        return this.brProdatihKarata;
    }
    
    public void setBrProdatihKarata(int brProdatihKarata) {
        this.brProdatihKarata = brProdatihKarata;
    }
    public int getBrRezervisanihKarata() {
        return this.brRezervisanihKarata;
    }
    
    public void setBrRezervisanihKarata(int brRezervisanihKarata) {
        this.brRezervisanihKarata = brRezervisanihKarata;
    }
    public Set<Nastupa> getNastupas() {
        return this.nastupas;
    }
    
    public void setNastupas(Set<Nastupa> nastupas) {
        this.nastupas = nastupas;
    }
    public Set<Rezervacija> getRezervacijas() {
        return this.rezervacijas;
    }
    
    public void setRezervacijas(Set<Rezervacija> rezervacijas) {
        this.rezervacijas = rezervacijas;
    }




}


