package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1



/**
 * DanId generated by hbm2java
 */
public class DanId  implements java.io.Serializable {


     private int idFest;
     private int idDan;

    public DanId() {
    }

    public DanId(int idFest, int idDan) {
       this.idFest = idFest;
       this.idDan = idDan;
    }
   
    public int getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(int idFest) {
        this.idFest = idFest;
    }
    public int getIdDan() {
        return this.idDan;
    }
    
    public void setIdDan(int idDan) {
        this.idDan = idDan;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DanId) ) return false;
		 DanId castOther = ( DanId ) other; 
         
		 return (this.getIdFest()==castOther.getIdFest())
 && (this.getIdDan()==castOther.getIdDan());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFest();
         result = 37 * result + this.getIdDan();
         return result;
   }   


}


