package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Festival generated by hbm2java
 */
public class Festival  implements java.io.Serializable {


     private Integer idFest;
     private Festivalgrupa festivalgrupa;
     private String ime;
     private String mesto;
     private Date od;
     private Date do_;
     private String facebook;
     private String twitter;
     private String instagram;
     private String youtube;
     private String opis;
     private int brKarataPoKorisniku;
     private int brKarataPoDanu;
     private int brojacpregleda;
     private int cenaPaket;
     private int cenaDan;
     private int status;
     private Set<Komentar> komentars = new HashSet<Komentar>(0);
     private Set<Media> medias = new HashSet<Media>(0);
     private Set<Dan> dans = new HashSet<Dan>(0);

    public Festival() {
    }

	
    public Festival(Festivalgrupa festivalgrupa, String ime, String mesto, Date od, Date do_, String facebook, String twitter, String instagram, String youtube, String opis, int brKarataPoKorisniku, int brKarataPoDanu, int brojacpregleda, int cenaPaket, int cenaDan, int status) {
        this.festivalgrupa = festivalgrupa;
        this.ime = ime;
        this.mesto = mesto;
        this.od = od;
        this.do_ = do_;
        this.facebook = facebook;
        this.twitter = twitter;
        this.instagram = instagram;
        this.youtube = youtube;
        this.opis = opis;
        this.brKarataPoKorisniku = brKarataPoKorisniku;
        this.brKarataPoDanu = brKarataPoDanu;
        this.brojacpregleda = brojacpregleda;
        this.cenaPaket = cenaPaket;
        this.cenaDan = cenaDan;
        this.status = status;
    }
    public Festival(Festivalgrupa festivalgrupa, String ime, String mesto, Date od, Date do_, String facebook, String twitter, String instagram, String youtube, String opis, int brKarataPoKorisniku, int brKarataPoDanu, int brojacpregleda, int cenaPaket, int cenaDan, int status, Set<Komentar> komentars, Set<Media> medias, Set<Dan> dans) {
       this.festivalgrupa = festivalgrupa;
       this.ime = ime;
       this.mesto = mesto;
       this.od = od;
       this.do_ = do_;
       this.facebook = facebook;
       this.twitter = twitter;
       this.instagram = instagram;
       this.youtube = youtube;
       this.opis = opis;
       this.brKarataPoKorisniku = brKarataPoKorisniku;
       this.brKarataPoDanu = brKarataPoDanu;
       this.brojacpregleda = brojacpregleda;
       this.cenaPaket = cenaPaket;
       this.cenaDan = cenaDan;
       this.status = status;
       this.komentars = komentars;
       this.medias = medias;
       this.dans = dans;
    }
   
    public Integer getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(Integer idFest) {
        this.idFest = idFest;
    }
    public Festivalgrupa getFestivalgrupa() {
        return this.festivalgrupa;
    }
    
    public void setFestivalgrupa(Festivalgrupa festivalgrupa) {
        this.festivalgrupa = festivalgrupa;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getMesto() {
        return this.mesto;
    }
    
    public void setMesto(String mesto) {
        this.mesto = mesto;
    }
    public Date getOd() {
        return this.od;
    }
    
    public void setOd(Date od) {
        this.od = od;
    }
    public Date getDo_() {
        return this.do_;
    }
    
    public void setDo_(Date do_) {
        this.do_ = do_;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getInstagram() {
        return this.instagram;
    }
    
    public void setInstagram(String instagram) {
        this.instagram = instagram;
    }
    public String getYoutube() {
        return this.youtube;
    }
    
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public int getBrKarataPoKorisniku() {
        return this.brKarataPoKorisniku;
    }
    
    public void setBrKarataPoKorisniku(int brKarataPoKorisniku) {
        this.brKarataPoKorisniku = brKarataPoKorisniku;
    }
    public int getBrKarataPoDanu() {
        return this.brKarataPoDanu;
    }
    
    public void setBrKarataPoDanu(int brKarataPoDanu) {
        this.brKarataPoDanu = brKarataPoDanu;
    }
    public int getBrojacpregleda() {
        return this.brojacpregleda;
    }
    
    public void setBrojacpregleda(int brojacpregleda) {
        this.brojacpregleda = brojacpregleda;
    }
    public int getCenaPaket() {
        return this.cenaPaket;
    }
    
    public void setCenaPaket(int cenaPaket) {
        this.cenaPaket = cenaPaket;
    }
    public int getCenaDan() {
        return this.cenaDan;
    }
    
    public void setCenaDan(int cenaDan) {
        this.cenaDan = cenaDan;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Set<Komentar> getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set<Komentar> komentars) {
        this.komentars = komentars;
    }
    public Set<Media> getMedias() {
        return this.medias;
    }
    
    public void setMedias(Set<Media> medias) {
        this.medias = medias;
    }
    public Set<Dan> getDans() {
        return this.dans;
    }
    
    public void setDans(Set<Dan> dans) {
        this.dans = dans;
    }




}


