package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Festivalgrupa generated by hbm2java
 */
public class Festivalgrupa  implements java.io.Serializable {


     private Integer idgrupe;
     private String opis;
     private Set<Festival> festivals = new HashSet<Festival>(0);

    public Festivalgrupa() {
    }

	
    public Festivalgrupa(String opis) {
        this.opis = opis;
    }
    public Festivalgrupa(String opis, Set<Festival> festivals) {
       this.opis = opis;
       this.festivals = festivals;
    }
   
    public Integer getIdgrupe() {
        return this.idgrupe;
    }
    
    public void setIdgrupe(Integer idgrupe) {
        this.idgrupe = idgrupe;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }
    public Set<Festival> getFestivals() {
        return this.festivals;
    }
    
    public void setFestivals(Set<Festival> festivals) {
        this.festivals = festivals;
    }




}


