package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Izvodjac generated by hbm2java
 */
public class Izvodjac  implements java.io.Serializable {


     private Integer idIzvodjac;
     private String ime;
     private Set<Nastupa> nastupas = new HashSet<Nastupa>(0);

    public Izvodjac() {
    }

	
    public Izvodjac(String ime) {
        this.ime = ime;
    }
    public Izvodjac(String ime, Set<Nastupa> nastupas) {
       this.ime = ime;
       this.nastupas = nastupas;
    }
   
    public Integer getIdIzvodjac() {
        return this.idIzvodjac;
    }
    
    public void setIdIzvodjac(Integer idIzvodjac) {
        this.idIzvodjac = idIzvodjac;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public Set<Nastupa> getNastupas() {
        return this.nastupas;
    }
    
    public void setNastupas(Set<Nastupa> nastupas) {
        this.nastupas = nastupas;
    }




}


