package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Komentar generated by hbm2java
 */
public class Komentar  implements java.io.Serializable {


     private KomentarId id;
     private Festival festival;
     private Korisnik korisnik;
     private String txt;
     private Integer ocena;
     private Date datum;

    public Komentar() {
    }

	
    public Komentar(KomentarId id, Festival festival, Korisnik korisnik, Date datum) {
        this.id = id;
        this.festival = festival;
        this.korisnik = korisnik;
        this.datum = datum;
    }
    public Komentar(KomentarId id, Festival festival, Korisnik korisnik, String txt, Integer ocena, Date datum) {
       this.id = id;
       this.festival = festival;
       this.korisnik = korisnik;
       this.txt = txt;
       this.ocena = ocena;
       this.datum = datum;
    }
   
    public KomentarId getId() {
        return this.id;
    }
    
    public void setId(KomentarId id) {
        this.id = id;
    }
    public Festival getFestival() {
        return this.festival;
    }
    
    public void setFestival(Festival festival) {
        this.festival = festival;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getTxt() {
        return this.txt;
    }
    
    public void setTxt(String txt) {
        this.txt = txt;
    }
    public Integer getOcena() {
        return this.ocena;
    }
    
    public void setOcena(Integer ocena) {
        this.ocena = ocena;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


