package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1



/**
 * KomentarId generated by hbm2java
 */
public class KomentarId  implements java.io.Serializable {


     private int idKomentar;
     private int idFest;

    public KomentarId() {
    }

    public KomentarId(int idKomentar, int idFest) {
       this.idKomentar = idKomentar;
       this.idFest = idFest;
    }
   
    public int getIdKomentar() {
        return this.idKomentar;
    }
    
    public void setIdKomentar(int idKomentar) {
        this.idKomentar = idKomentar;
    }
    public int getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(int idFest) {
        this.idFest = idFest;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KomentarId) ) return false;
		 KomentarId castOther = ( KomentarId ) other; 
         
		 return (this.getIdKomentar()==castOther.getIdKomentar())
 && (this.getIdFest()==castOther.getIdFest());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdKomentar();
         result = 37 * result + this.getIdFest();
         return result;
   }   


}


