package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1



/**
 * MediaId generated by hbm2java
 */
public class MediaId  implements java.io.Serializable {


     private int idFest;
     private int idmedia;

    public MediaId() {
    }

    public MediaId(int idFest, int idmedia) {
       this.idFest = idFest;
       this.idmedia = idmedia;
    }
   
    public int getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(int idFest) {
        this.idFest = idFest;
    }
    public int getIdmedia() {
        return this.idmedia;
    }
    
    public void setIdmedia(int idmedia) {
        this.idmedia = idmedia;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MediaId) ) return false;
		 MediaId castOther = ( MediaId ) other; 
         
		 return (this.getIdFest()==castOther.getIdFest())
 && (this.getIdmedia()==castOther.getIdmedia());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFest();
         result = 37 * result + this.getIdmedia();
         return result;
   }   


}


