package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1



/**
 * NastupaId generated by hbm2java
 */
public class NastupaId  implements java.io.Serializable {


     private int idIzvodjac;
     private int idFest;
     private int idDan;

    public NastupaId() {
    }

    public NastupaId(int idIzvodjac, int idFest, int idDan) {
       this.idIzvodjac = idIzvodjac;
       this.idFest = idFest;
       this.idDan = idDan;
    }
   
    public int getIdIzvodjac() {
        return this.idIzvodjac;
    }
    
    public void setIdIzvodjac(int idIzvodjac) {
        this.idIzvodjac = idIzvodjac;
    }
    public int getIdFest() {
        return this.idFest;
    }
    
    public void setIdFest(int idFest) {
        this.idFest = idFest;
    }
    public int getIdDan() {
        return this.idDan;
    }
    
    public void setIdDan(int idDan) {
        this.idDan = idDan;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NastupaId) ) return false;
		 NastupaId castOther = ( NastupaId ) other; 
         
		 return (this.getIdIzvodjac()==castOther.getIdIzvodjac())
 && (this.getIdFest()==castOther.getIdFest())
 && (this.getIdDan()==castOther.getIdDan());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIzvodjac();
         result = 37 * result + this.getIdFest();
         result = 37 * result + this.getIdDan();
         return result;
   }   


}


