package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nastupa generated by hbm2java
 */
public class Nastupa  implements java.io.Serializable {


     private NastupaId id;
     private Dan dan;
     private Izvodjac izvodjac;
     private Date pocinje;
     private Date zavrsava;

    public Nastupa() {
    }

    public Nastupa(NastupaId id, Dan dan, Izvodjac izvodjac, Date pocinje, Date zavrsava) {
       this.id = id;
       this.dan = dan;
       this.izvodjac = izvodjac;
       this.pocinje = pocinje;
       this.zavrsava = zavrsava;
    }
   
    public NastupaId getId() {
        return this.id;
    }
    
    public void setId(NastupaId id) {
        this.id = id;
    }
    public Dan getDan() {
        return this.dan;
    }
    
    public void setDan(Dan dan) {
        this.dan = dan;
    }
    public Izvodjac getIzvodjac() {
        return this.izvodjac;
    }
    
    public void setIzvodjac(Izvodjac izvodjac) {
        this.izvodjac = izvodjac;
    }
    public Date getPocinje() {
        return this.pocinje;
    }
    
    public void setPocinje(Date pocinje) {
        this.pocinje = pocinje;
    }
    public Date getZavrsava() {
        return this.zavrsava;
    }
    
    public void setZavrsava(Date zavrsava) {
        this.zavrsava = zavrsava;
    }




}


