package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Poruka generated by hbm2java
 */
public class Poruka  implements java.io.Serializable {


     private Integer idPoruke;
     private Korisnik korisnik;
     private String sadrzaj;
     private Date datum;

    public Poruka() {
    }

    public Poruka(Korisnik korisnik, String sadrzaj, Date datum) {
       this.korisnik = korisnik;
       this.sadrzaj = sadrzaj;
       this.datum = datum;
    }
   
    public Integer getIdPoruke() {
        return this.idPoruke;
    }
    
    public void setIdPoruke(Integer idPoruke) {
        this.idPoruke = idPoruke;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public String getSadrzaj() {
        return this.sadrzaj;
    }
    
    public void setSadrzaj(String sadrzaj) {
        this.sadrzaj = sadrzaj;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }




}


