package db;
// Generated Feb 16, 2017 3:47:35 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rezervacija generated by hbm2java
 */
public class Rezervacija  implements java.io.Serializable {


     private Integer idRez;
     private Dan dan;
     private Korisnik korisnik;
     private int tip;
     private int status;
     private Date datum;
     private int brojkarata;

    public Rezervacija() {
    }

    public Rezervacija(Dan dan, Korisnik korisnik, int tip, int status, Date datum, int brojkarata) {
       this.dan = dan;
       this.korisnik = korisnik;
       this.tip = tip;
       this.status = status;
       this.datum = datum;
       this.brojkarata = brojkarata;
    }
   
    public Integer getIdRez() {
        return this.idRez;
    }
    
    public void setIdRez(Integer idRez) {
        this.idRez = idRez;
    }
    public Dan getDan() {
        return this.dan;
    }
    
    public void setDan(Dan dan) {
        this.dan = dan;
    }
    public Korisnik getKorisnik() {
        return this.korisnik;
    }
    
    public void setKorisnik(Korisnik korisnik) {
        this.korisnik = korisnik;
    }
    public int getTip() {
        return this.tip;
    }
    
    public void setTip(int tip) {
        this.tip = tip;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }
    public int getBrojkarata() {
        return this.brojkarata;
    }
    
    public void setBrojkarata(int brojkarata) {
        this.brojkarata = brojkarata;
    }




}


